In [1]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('spam.csv',encoding='ISO-8859-1')

In [6]:
df.sample(5)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
1408,ham,"I've got ten bucks, jay is being noncomittal",NaN,NaN,NaN
5469,ham,Ok lor.,NaN,NaN,NaN
181,ham,Lol no. U can trust me.,NaN,NaN,NaN
2802,spam,FreeMsg>FAV XMAS TONES!Reply REAL,NaN,NaN,NaN
3693,ham,Ok im not sure what time i finish tomorrow but...,NaN,NaN,NaN

In [7]:
df.shape

(5572, 5)

In [8]:
# stage of project
# 1. Data cleaning
# 2. EDA
# 3. Text Preprocessing
# 4. Model building
# 5. Evaluation
# 6. Improvement
# 7. website
# 8. Deploy

# 1. Data Cleaning

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [10]:
# drop last 3 cols because have less value 
df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace=True)

In [11]:
df.sample(5)

       v1                                                 v2
3087  ham  'Wnevr i wana fal in luv vth my books, My bed ...
445   ham  Sorry, my battery died, I can come by but I'm ...
4660  ham                                      Ok no prob...
5046  ham                    Hmmm.still we dont have opener?
2659  ham                                              Ok...

In [12]:
# rename the column because unablile to  understand about the columns
df.rename(columns={'v1':'target','v2':'text'},inplace=True)

In [13]:
df.head()

  target                                               text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [14]:
# give label 
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [16]:
df['target'] = encoder.fit_transform(df['target'])

In [17]:
df.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [18]:
# checking that missing values are present or not 
df.isnull().sum()

target    0
text      0
dtype: int64

In [23]:
#check of duplicate values
df.duplicated().sum()

403

In [26]:
# remove duplicates
df = df.drop_duplicates(keep='first')

In [27]:
df.duplicated().sum()

0

In [28]:
df.shape

(5169, 2)

## Now we are done with  our cleaning part

# 2. EDA