## Data Analysis Process

1. Asking Questions
2. Data Wrangling<br>
    a. Gathering Data
        - i. CSV files
        - ii. APIs
        - iii. Web Scraping
        - iv. Databases
    b. Assessing Data<br>
    c. Cleaning Data
3. Exploratory Data Analysis
4. Drawing Conclusion
5. Comunicating Results

## 1b. Data Accessing

In this step , the data is to be understood more deeply. Before implementing methods to clean it , you will definitely need to have a better idea about what the data is about .

# Types of Unclean Data
There are 2 kinds of unclean data 

* `Dirty Data (data with Quality issues)`: Dirty data, also known as low quality data . Low quality data has content issues .

   * Duplicated data
   * Missing data 
   * Corrupt data
   * Inaccurate Data

* `Messy Data( Data With tidiness issues)`: Messy data , also known as untidy data. Untidy data has structural issues . Tidy data has the following properties:
    * Each variable forms a column
    * Each observation forms a row 
    * Each observational unit forms a table

In [1]:
import pandas as pd
import numpy as np

In [2]:
patients = pd.read_csv('patients.csv')
treatments = pd.read_csv('treatments.csv')
adverse_reactions = pd.read_csv('adverse_reactions.csv')
treatments_cut = pd.read_csv('treatments_cut.csv')

In [3]:
patients.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

# What Is the goal of this analysis
* Are we analyzing general health trends?
* Are we trying to identify patients at risk based on BMI?
* Is this  for reporting , diagnosis support or outreach?

# 🧑‍🤝‍🧑 Who is the audience?
* Doctors or healthcare providers ?
* Insurance Companies?
* Public health officials ?
* A data science team building predictive medels?✅

# What does each row represent ?
* Each row appears to represent a unique patient record, including personal and health information.

# What do the columns means?
* `patient_id` :- Unique identifier for each patient
* `assigned_sex` :- Gender assigned at registration(may differ from biological)
* `given_name , surname` :- Patient's full name
* `address ,city,state,zip_code,country` :- Location info
* `contact` :- Email/Phone - some messay data here(merged)
* `birthdata` :- Patient's dat pf birth
* `weight(lbs)` :- Body weight
* `height(inches)` :- Body height
* `Bmi`:- Body Mass Index(Calculated from height and weight)

# About the dataset that  is important 

* Who collected this  data , and when ?
* Are any fields calculated (e.g.,`bmi`) or manually entered?
* Are names and contact info real or anonymized?

# 🔍 2. Ask Descriptive Questions (What happened?)
These help you summarize the dataset:

In [4]:
# How many rows and columns are there
patients.shape

(503, 14)

In [6]:
# Are there missing values?
patients.isnull().sum()

patient_id       0
assigned_sex     0
given_name       0
surname          0
address         12
city            12
state           12
zip_code        12
country         12
contact         12
birthdate        0
weight           0
height           0
bmi              0
dtype: int64

In [7]:
# What are the data types?
patients.dtypes

patient_id        int64
assigned_sex     object
given_name       object
surname          object
address          object
city             object
state            object
zip_code        float64
country          object
contact          object
birthdate        object
weight          float64
height            int64
bmi             float64
dtype: object

# which column in which type 
* Categorical :- assigned_sex, city ,state, country
* Numeric:-patient_id,weight, height,bmi
* Data:- birthdate(converted to data end time )
* mix :- given_name,surname

In [ ]:
# Range of values in numerical colums 
# range  only  find in numerical column it is not use for categorical columns 
patients.describe()

       patient_id      zip_code      weight      height         bmi
count  503.000000    491.000000  503.000000  503.000000  503.000000
mean   252.000000  49084.118126  173.434990   66.634195   27.483897
std    145.347859  30265.807442   33.916741    4.411297    5.276438
min      1.000000   1002.000000   48.800000   27.000000   17.100000
25%    126.500000  21920.500000  149.300000   63.000000   23.300000
50%    252.000000  48057.000000  175.300000   67.000000   27.200000
75%    377.500000  75679.000000  199.500000   70.000000   31.750000
max    503.000000  99701.000000  255.900000   79.000000   37.700000

In [13]:
patients[patients['weight']==patients['weight'].max()]
# what this is line is saying :- find the patient with maximum weight in patients list and take it for me and all details about the patient

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
485,486,male,Trifon,Izmailov,3697 Drainer Avenue,Fort Walton Beach,FL,32548.0,United States,TrifonIzmailov@fleckens.hu1 850 659 0417,2/15/1973,255.9,74,32.9