# Email Spam Filter

## Problem Statement
* Email is a key communication tool today, but spam emails have become a major issue, cluttering inboxes and posing threats like phishing and malware. To tackle this , there's a need for an efficient machine learning system that can automatically detect and filter
spam . By learning patterns in email content , such a systen can improve user experience and enhance security.

## Objective
The Primary objective of this project is to build a robust spam detection model that can accurately classify emails as spam or legitimate(ham) based on their content and metadata.

## Data Description
The dataset consists of a collection of emails labeled as either spam or legitimate (ham). Each email sample is represented by features such as sender email address, subject line , email body content , and attachments. The dataset provides a balanced
distribution of spam and ham emails, enabling the development of a model that can effectively differentiate between the two classes.

## Project Work Flow
### Data Wrangling:
* Load the dataset containing the "text" and "label" columns.
* Understanding the data
* Hnadle any missing values or duplicates if present

### Exploratory Data Analysis(EDA):
* Perform basic exploratory analysis to understand the characterstics of the email text data.
* Visualize the distribution of the spam and ham emails using histograms or pie charts.
* Explore the length of emails(number of characters or words) in each category .
* Identify common keywords or phrases in spam and ham emails through word frequency analysis.

# Import all Important libraries
## ! pip install pandas 
## ! pip install nltk
## ! pip install scikit-learn

In [1]:
import string
import nltk
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
import warnings
import plotly.express as px
import string
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, mean_squared_error
from sklearn.metrics import roc_curve, roc_auc_score,auc
from sklearn.model_selection import cross_val_predict
from sklearn import metrics
warnings.simplefilter(action='ignore', category=FutureWarning)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...

# Data Wrangling

In [2]:
#Load the dataset
data = pd.read_csv("emails.csv")

In [3]:
## Copy the data 

spam_df = data.copy()
spam_df.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

### Understanding the data 
* text :- Conteains the subject of the email.
* spam :- contains binary values '0' indicting ham and '1' indicating spam

In [4]:
spam_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5728 entries, 0 to 5727
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    5728 non-null   object
 1   spam    5728 non-null   int64
dtypes: int64(1), object(1)
memory usage: 89.6+ KB

## Exploratory Data Analysis (EDA)
* Statistics Summary 
* Indentifying Missing values
* Hnadling Missing values
* Removing Duplicate records
* Visualization

##### Statistic Summary

In [6]:
spam_df.describe().T

       count      mean       std  min  25%  50%  75%  max
spam  5728.0  0.238827  0.426404  0.0  0.0  0.0  0.0  1.0

In [7]:
spam_df.dtypes

text    object
spam     int64
dtype: object