In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('play_tennis.csv')
data.head()
data.drop(columns=['day'],inplace=True)

In [3]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [4]:
# problem 1
 
# Outlook = sunny , temp=Hot, Humidity =High, wind=weak
# Play or No Play?

In [6]:
# Solution
# P(Yes / Sunny,Hot, Weak) = P(Sunny / Yes) * P(Hot / Yes) * P(High / Yes) * P(Weak / Yes) * P(yes)

# P(No / Sunny, Hot, Weak) = p(sunny / No) * P(Hot / No) * P(Weak / No) * P(No)

# Compare and decide using the Maximum a posteriori rule

In [7]:
# Problem 2 

# OutLook = Overcast , Temp = Cold, Humidity = Low, Wind = Weak

# Play or No Play?

In [8]:
# Solution

# P(Yes / Overcast, Cold, Low, Weak) = P(Overcast / Yes) * p(Cold / Yes) * P(Low / Yes) * P(weak / Yes)

# P(No / Overcast , Cold, Low ,weak) = P(Overcast / No) * P(Cold / No) * p(Low / No) * P(weak  / no)

# Compare and decide using the maximum a posteriori rule

In [ ]:
# Training

# Lookup table (Dictionary) 

# Testing

In [9]:
#P(Yes)
#P(No)

In [10]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [11]:
py = 9/14
pn=5/14

In [12]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [13]:
# Outlook
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [14]:
Pon = 0
Prn = 2/5
Psn = 3/5

Poy = 4/9
Pry = 3/9
Psy= 2/9

In [15]:
# temp
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [16]:
PCoolNO = 1/5
PhotNo = 2/5
PMildNo = 2/5

PCoolYes = 3/9
PHotYes = 2/9
PMidYes = 4/9

In [17]:
# Humidity 

pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [18]:
PHighNo = 4/5
PNormalNO = 1/5

PHighYes = 3 / 9
PNormalYes = 6/9

In [19]:
# Wind
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [20]:
PstronNo = 3/5
PWeakNO = 2/5

PstronYes = 3/9
PWeakYes = 6/9

In [21]:
# OutLook = Sunny , Temp = Hot, Humidity = High, Wind = weak

PYes = py*Psy*PHotYes*PHighYes*PWeakYes

In [22]:
PYes

0.007054673721340388

In [23]:
PNo = pn*Psn*PhotNo*PHighNo*PWeakNO

In [24]:
PNo

0.02742857142857143

In [ ]:
# No Play